# Generated by Django 4.1.2 on 2022-11-21 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dueño', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': 'mascotas',
            },
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=100)),
                ('tratamiento', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaAPP.mascota')),
            ],
            options={
                'verbose_name': 'ConsultasMedica',
                'verbose_name_plural': 'ConsultasMedicas',
            },
        ),
    ]
