# Generated by Django 4.1.2 on 2022-11-22 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinariaAPP', '0003_vacuna_cirugia'),
    ]

    operations = [
        migrations.CreateModel(
            name='dueño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueño', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'dueño',
                'verbose_name_plural': 'dueños',
            },
        ),
        migrations.AlterField(
            model_name='mascota',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaAPP.dueño'),
        ),
    ]
